---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: sudo Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull yasha145/dockerproject_1:latest

    - name: Stoping and removing container image
      shell: docker stop calc && docker rm calci

    - name: running container
      shell: docker run -it -d --name calci yasha145/dockerproject_1:latest && gnome-terminal -- bash -c "docker attach calci; exec bash"
